"""!
@file __init__.py
@brief Initializes the 'proto' package for the Speech Detection Service.

This file marks the directory as a Python package. This directory is intended
to hold the Python files generated by the Protocol Buffer compiler (protoc)
from `.proto` definition files. These generated files include message classes
and gRPC client/server stubs.
"""
