# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: vision.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'vision.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cvision.proto\x12\x06vision\"\x1d\n\x0c\x46rameRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\"E\n\x0b\x46\x61\x63\x65Request\x12\x12\n\nface_image\x18\x01 \x01(\x0c\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x02 \x01(\x05\x12\x11\n\tlandmarks\x18\x03 \x03(\x02\"N\n\x0eVisionResponse\x12#\n\x05\x66\x61\x63\x65s\x18\x01 \x03(\x0b\x32\x14.vision.DetectedFace\x12\x17\n\x0fperson_detected\x18\x02 \x01(\x08\"v\n\x0c\x44\x65tectedFace\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x12\n\nface_image\x18\x02 \x01(\x0c\x12\x11\n\tlandmarks\x18\x03 \x03(\x02\x12\t\n\x01x\x18\x04 \x01(\x05\x12\t\n\x01y\x18\x05 \x01(\x05\x12\r\n\x05width\x18\x06 \x01(\x05\x12\x0e\n\x06height\x18\x07 \x01(\x05\"G\n\x0f\x45motionResponse\x12\x0f\n\x07\x65motion\x18\x01 \x01(\t\x12\x12\n\nconfidence\x18\x02 \x01(\x02\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x03 \x01(\x05\"M\n\x0eSpeechResponse\x12\x13\n\x0bis_speaking\x18\x01 \x01(\x08\x12\x15\n\rspeaking_time\x18\x02 \x01(\x02\x12\x0f\n\x07\x66\x61\x63\x65_id\x18\x03 \x01(\x05\"5\n\x10\x43ombinedResponse\x12!\n\x08speakers\x18\x01 \x03(\x0b\x32\x0f.vision.Speaker\"\x82\x01\n\x07Speaker\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x15\n\rspeaking_time\x18\x02 \x01(\x02\x12\x13\n\x0bis_speaking\x18\x03 \x01(\x08\x12\x0f\n\x07\x65motion\x18\x04 \x01(\t\x12\x1a\n\x12\x65motion_confidence\x18\x05 \x01(\x02\x12\x12\n\nface_image\x18\x06 \x01(\x0c\x32M\n\rVisionService\x12<\n\x0c\x41nalyzeFrame\x12\x14.vision.FrameRequest\x1a\x16.vision.VisionResponse2P\n\x0e\x45motionService\x12>\n\x0e\x41nalyzeEmotion\x12\x13.vision.FaceRequest\x1a\x17.vision.EmotionResponse2U\n\x16SpeechDetectionService\x12;\n\x0c\x44\x65tectSpeech\x12\x13.vision.FaceRequest\x1a\x16.vision.SpeechResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vision_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_FRAMEREQUEST']._serialized_start=24
  _globals['_FRAMEREQUEST']._serialized_end=53
  _globals['_FACEREQUEST']._serialized_start=55
  _globals['_FACEREQUEST']._serialized_end=124
  _globals['_VISIONRESPONSE']._serialized_start=126
  _globals['_VISIONRESPONSE']._serialized_end=204
  _globals['_DETECTEDFACE']._serialized_start=206
  _globals['_DETECTEDFACE']._serialized_end=324
  _globals['_EMOTIONRESPONSE']._serialized_start=326
  _globals['_EMOTIONRESPONSE']._serialized_end=397
  _globals['_SPEECHRESPONSE']._serialized_start=399
  _globals['_SPEECHRESPONSE']._serialized_end=476
  _globals['_COMBINEDRESPONSE']._serialized_start=478
  _globals['_COMBINEDRESPONSE']._serialized_end=531
  _globals['_SPEAKER']._serialized_start=534
  _globals['_SPEAKER']._serialized_end=664
  _globals['_VISIONSERVICE']._serialized_start=666
  _globals['_VISIONSERVICE']._serialized_end=743
  _globals['_EMOTIONSERVICE']._serialized_start=745
  _globals['_EMOTIONSERVICE']._serialized_end=825
  _globals['_SPEECHDETECTIONSERVICE']._serialized_start=827
  _globals['_SPEECHDETECTIONSERVICE']._serialized_end=912
# @@protoc_insertion_point(module_scope)
